config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/dashboard'
  post 'posts', to: 'posts#create'
  get 'posts/success', to: 'posts#success', as: 'success'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :image, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only:
  :dashboard
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def dashboard
    @post = Post.new
  end
  def create
    content = params[:post][:content].gsub('spoiler', '')
    @post = Post.new(content: content, title: params[:post][:title], image: params[:post][:image])
    if @post.save
      redirect_to success_path
    else
      render 'dashboard'
    end
  end

  def success
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Bootstrap CSS 4.6.0 VERSION-->  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
  <a class="navbar-brand" href="#">Aroma</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to('Inicio', posts_index_path, class: 'nav-link') %>
      <%= link_to('Dashboard', posts_dashboard_path, class: 'nav-link') %>
    </div>
  </div>
</nav>

  <div class="container">
    <%= yield %>
  </div>


    <footer class="container-fluid text-white bg-dark mt-5">
      <div class="container icons d-flex justify-content-between align-items-center pt-3">
      <h3>Aroma</h3>
        <ul class="footer-icons list-style-none text-white text-decoration-none">
            <li class="d-inline ">
                <a href="https://www.github.com"><i class="fab fa-github-square fa-2x pl-2" style="color:#ffffff"></i></a>
            </li>
            <li class="d-inline">
              <a href="https://www.linkedin.com"><i class="fab fa-linkedin fa-2x pl-2" style="color:#ffffff"></i></a>
            </li>
            <li class="d-inline">
                <a href="https://www.twitter.com"><i class="fab fa-twitter-square fa-2x pl-2" style="color:#ffffff"></i></a>
            </li>
            <li class="d-inline">
              <a href="https://www.facebook.com"><i class="fab fa-facebook-square fa-2x pl-2" style="color:#ffffff"></i></a>
            </li>
          </ul>
        </div>
        <p class="footer-rights text-center pb-3 mb-0">All Rights Reserved 2021. San José, Costa Rica</p>
    </footer>
       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </body>
</html>

app/views/posts/dashboard.html.erb
<div class="container mt-5">
<h1>Crear post</h1>

<% if @post.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@post.errors.count, "error") %> prohibited this
post from being saved:</h2>
<ul>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<%= form_with model: @post do |form| %>
 <div class="form-group">
 Title:
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
  Image Url
  <%= form.text_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
  Content:
  <%= form.text_area :content, size: "60x10", class: 'form-control' %>
  </div>
  
  <%= form.submit 'submit', class:'btn btn-danger' %>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="container text-center my-5 text-danger">
<h1>Fragancias que enamoran</h1>
</div>
<div class="card-deck">
<% @posts.each do |post| %>
  <div class="card">
    <img src="<%= post.image%>" class="card-img-top" alt="<%= post.title%>">
    <div class="card-body">
      <h5 class="card-title"><%= post.title%></h5>
      <p class="card-text"><%= post.content%></p>
      <p class="card-text"><small class="text-muted"><%= post.created_at%></small></p>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/success.html.erb
<h1>Éxito!!</h1>